addpath(genpath('C:\Users\petnov\Dropbox\shared\'));
addpath(genpath('C:\Users\petnov\Dropbox\mesh scripts'))
enableVTK;

%H0 = read_VTK( fullfile( TORSO_MODEL_DIR , 'HEART_with_UPS_louie.vtk' ) ); %this is louie's heart!
H_mesh = read_CHASTE( 'D:\ARVC meshing automatic\patients\patient05\chaste_gmsh\HEART');

H0 = read_VTK('D:\ARVC meshing automatic\patients\patient05\ARVC05_ecgi_mesh.vtk'); %use the original ecgi mesh, not the clipped one!!


%chaste works in cm, our meshes are built in mm (BE CAREFUL WHEN LOCATING
%INDICES 



%%

H1 = read_VTK(  'D:\ARVC meshing automatic\patients\patient05\HEART.vtk'); %our target heart
[EPI1,LV1,RV1,~,MAT1] = HEARTparts( H1 );

plotMESH( H0 ,'ne');
hplotMESH( H1 , 'ne' ,'FaceColor',[1 1 1]*0.6)
headlight; axis(objbounds);

%HD_loaded = load('Z:\Dropbox\patients\HD.mat');

%%

u = loadv( 'D:\ARVC meshing automatic\patients\patient05\mpp\Hmapping' , 'u' ); %transfer matrix u
%this is a function converting coordinates from H0 to H1
%it is generated by running the mpp_Heart_Mapping Function of Ernesto s
%pipeline!!


%check if the two meshes are in the same units of length by plotting side
%by side, if they are not, convert the ECGi or chaste mesh unit into mm
%H0.xyz = H0.xyz*10;

if 1
HD = H0;
HD.xyz = u( HD.xyz );

plotMESH( HD ,'ne');
hplotMESH( H1 , 'ne' ,'FaceColor',[1 1 1]*0.6)
headlight; axis(objbounds);
axis off
end


EPI1 = Mesh(EPI1);

%%
%find the point in HD (ecgi mesh registered to the chaste mesh) corresponding to each of the nodes of thr chaste mesh 
closest_points = vtkClosestPoint(   Mesh(HD) ,EPI1.xyz);
tissue_info = fractionation_counter('D:\ChrisReconstructions\ARVC5\ARVC5_Baseline.mat');
epi_cell_property = tissue_info(closest_points);

%check that the epicardial surface contains the expected fibrotic and scar
%patterns
plotMESH( EPI1, 'edgecolor','none' , 'cdata' , epi_cell_property' ,'facecolor','interp' )
axis off
headlight
%give all of the nodes which are not part of the epicardium a 0 label

mesh_cell_property = zeros(size(H_mesh.xyz,1),1);
mesh_cell_property(1:size(epi_cell_property,2)) =epi_cell_property;

%now extend the scar into the mid-myocardium
%for the RV,just make the scar as thick as the ventricles and for the lv,
%set a limit of 5mm (arbitrary)





fid = fopen('D:\ARVC meshing automatic\patients\patient05\fibrosis.txt','w');
fprintf(fid,'%d\n',mesh_cell_property);
fclose(fid)

