addpath(genpath('C:\Users\petnov\Dropbox\shared - copy'));
enableVTK;
TORSO_MODEL_DIR = 'D:\ARVC meshing automatic\patients\patient06\chaste06\';
SUBJECT_DIR = 'D:\ARVC meshing automatic\patients\patient06';
%H0 = read_VTK( fullfile( TORSO_MODEL_DIR , 'HEART_with_UPS_louie.vtk' ) ); %this is louie's heart!
vest=load(strcat(SUBJECT_DIR,'mpp\','fittedVEST.mat'));
H0 = read_VTK('C:\Users\petnov\Dropbox\shared - copy\MeshPersonalizationPipeline\TORSO\HEART.vtk');


HV=read_CHASTE(strcat(SUBJECT_DIR,'\chaste06_edge_0.4_RV_0.15\','HEART'));

figure()
hplotMESH(HV,'ne')
headlight
%chaste works in cm, our meshes are built in mm (BE CAREFUL WHEN LOCATING
%INDICES OF ROOTS, always compare the same type of file eg vtk generated by
%pipeline or convert units

LV0_roots = [ 157258 , 129516 , 140114 , 131341 ];
RV0_roots = [ 198857 , 209309 , 186671 ];

tri=dlmread(strcat(SUBJECT_DIR,'\HM\HMclean.tri'),',');
xyzs=dlmread(strcat(SUBJECT_DIR,'\HM\HMclean.xyz'),',');



HM=struct;
HM.tri=tri+1;
HM.xyz=xyzs;

HM=load(strcat(SUBJECT_DIR,'\mpp\HM_0.1_350ITs.mat'));

%eval( HEART.TITLE );
HEART=HM.HM;
HEART.celltype=5;


  [~,M] = jigsaw_surface_2_volume( HEART , 'delfront' , 'absolute','geom_feat',true,'hfun_hmax',0.5,'hfun_hmin',0.15);

Htetgen = gmshfn(M,['v']);


write_VTK(Htetgen,strcat(SUBJECT_DIR,'\HM\HV_0.2.vtk'),'binary')
write_VTK(M,strcat(SUBJECT_DIR,'\HM\M_0.2.vtk'),'binary')

figure()
hplotMESH(HM.HM,'ne')
headlight

distance=@(x,y) sqrt((x(:,1)-y(:,1)).^2+(x(:,2)-y(:,2)).^2+(x(:,3)-y(:,3)).^2);
H2=load(strcat(SUBJECT_DIR,'\mpp\HM_0.1_350ITs.mat'));
H=load(strcat(SUBJECT_DIR,'\mpp\HM_0.1_310ITs.mat'));
H3=load(strcat(SUBJECT_DIR,'\mpp\HM_0.2.mat'));

    idx_epi=vtkClosestPoint(H2.EPIms,H2.RVms.xyz(1:size(H2.RVms.xyz,1),:));
    
    
    dists=distance(H2.EPIms.xyz(idx_epi,:),H2.RVms.xyz(1:size(H2.RVms.xyz,1),:));

       dist_mean_2=mean(dists);
       
       
    idx_epi=vtkClosestPoint(H.EPIms,H.RVms.xyz(1:size(H.RVms.xyz,1),:));
    
    
    dists1=distance(H.EPIms.xyz(idx_epi,:),H.RVms.xyz(1:size(H.RVms.xyz,1),:));

       dist_mean_original=mean(dists1);
       
    idx_epi=vtkClosestPoint(H3.EPIms,H3.RVms.xyz(1:size(H3.RVms.xyz,1),:));
    
    
    dists2=distance(H3.EPIms.xyz(idx_epi,:),H3.RVms.xyz(1:size(H3.RVms.xyz,1),:));

       dist_mean_vert_thin=mean(dists2);
       
       
       [series,centres]=hist(dists,500);
       [series1,centres1]=hist(dists1,centres,500);
       [series2,centres2]=hist(dists2,centres,500);

       
       figure()
       bar(centres,100*series./size(H2.RVms.xyz,1),'facecolor','m')
       hold on
       
       bar(centres1,100*series1./size(H.RVms.xyz,1),'facecolor','g')
              bar(centres1,100*series2./size(H3.RVms.xyz,1),'facecolor','b')

       alpha(0.4)
        legend({'very thin','thin','normal'})
        
        
       
       bar([centres;centres1],[series;series1],'grouped')
       
       
       bar(centres,series,1,'Facecolor','r')
       hold on
       bar(centres,series1,0.5,'Facecolor','g')

       

figure()
plotMESH( H0 , 'ne' );
hplot3d( H0.xyz( LV0_roots ,:) , 'o1kb20' );
hplot3d( H0.xyz( RV0_roots ,:) , 'o1kr20' );
headlight


%%

H1 = read_VTK(  'D:\ARVC meshing automatic\patients\patient06\HEART_0.70.vtk'); %our target heart

%roots=csvread('D:\ARVC meshing automatic\patients\patient06\eikonal06_fine_rootNodes.csv');


    [EPI1,LV1,RV1,~,MAT1] = HEARTparts( H1 );

    closest_epi=vtkClosestPoint(EPI1,H1.xyz(roots_coarse(1),:))
    closest_epi_coord=EPI1.xyz(closest_epi,:);
    root_endo=H1.xyz(roots_coarse(1),:);
    
    dist= sqrt((closest_epi_coord(1)-root_endo(1))^2+(closest_epi_coord(2)-root_endo(2))^2+(closest_epi_coord(3)-root_endo(3))^2);
    
% 
% figure()
% plotMESH( H1 , 'ne' );
% hplot3d( H1.xyz( horzcat(roots(1:3), roots(5)) ,:) , 'o1kb20' );
% headlight
% 
% pos_new=[29.52 -59.82 -19.88];
% distance=@(v1,v2) sqrt((v1(:,1)-v2(:,1)).^2+(v1(:,2)-v2(:,2)).^2+(v1(:,3)-v2(:,3)).^2);
% dist=distance(pos_new,H1.xyz);
% [~,id]=min(dist);
% 
% pos_new2=[40.53 -83.21 21.36];
% dist=distance(pos_new2,H1.xyz);
% [~,id2]=min(dist);
% 
% roots_new= vertcat(roots(1:5),roots(7) );
% 
% %dlmwrite('D:\ARVC meshing automatic\patients\patient06\eikonal06_fine_rootNodesRootRVSeptUpAnteriorForward.csv',roots_new,'delimiter',',','precision',10);
% 
% 
% figure()
% %plotMESH( H0 ,'ne');
% hplotMESH( H1 , 'ne' ,'FaceColor',[1 1 1]*0.6)
% hplot3d( H1.xyz( vertcat(roots_new+1),:) , 'o1kb20' );
% headlight; axis(objbounds);

%HD_loaded = load('Z:\Dropbox\patients\HD.mat');

%%
%H1_full = read_CHASTE(  'D:\ARVC meshing automatic\patients\patient06\chaste06\HEART'); %our target heart
